# Generated by Django 4.2.7 on 2024-03-15 19:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("degree", models.CharField(max_length=255)),
                ("college_institute", models.CharField(max_length=255)),
                ("year_of_completion", models.CharField(max_length=4)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorExperience",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("has_experience", models.BooleanField(default=False)),
                ("experience", models.CharField(blank=True, max_length=2, null=True)),
                ("has_clinic", models.BooleanField(default=False)),
                ("clinic", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=31)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="images/profile/")),
                ("phone", models.CharField(blank=True, max_length=15, null=True)),
                (
                    "dob",
                    models.CharField(
                        blank=True,
                        choices=[("Example1", "Example1"), ("Example2", "Example2")],
                        max_length=15,
                        null=True,
                    ),
                ),
                ("height", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("age", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weight", models.FloatField(blank=True, null=True)),
                ("is_premium", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SellerBusiness",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("street_address", models.CharField(max_length=255)),
                ("pin_code", models.CharField(max_length=31)),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.country")),
                ("currency", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.currency")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="business", to="users.profile"
                    ),
                ),
                ("state", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.state")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OtherDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("detail", models.CharField(max_length=255)),
                (
                    "award_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="others", to="users.doctordetail"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ExperienceLetter",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="files/letters/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "doc", "pdf"])],
                    ),
                ),
                (
                    "doctor_experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="letters",
                        to="users.doctorexperience",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="DoctorPersonalInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gender", models.CharField(choices=[("Male", "Male"), ("Female", "Female")], max_length=8)),
                ("bio", models.CharField(blank=True, max_length=255, null=True)),
                ("language", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="users.language")),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="personal", to="users.profile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="doctorexperience",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="experience", to="users.profile"
            ),
        ),
        migrations.AddField(
            model_name="doctordetail",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="detail", to="users.profile"
            ),
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        upload_to="files/certificate/",
                        validators=[django.core.validators.FileExtensionValidator(["jpg", "doc", "pdf"])],
                    ),
                ),
                (
                    "award_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to="users.doctordetail",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankDetail",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("account_name", models.CharField(max_length=255)),
                ("account_phone", models.CharField(max_length=15)),
                ("gst_number", models.CharField(max_length=31)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="bank_detail", to="users.profile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="BankAttachment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="attachment", to="users.profile"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AttachmentBusinessDoc",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_type",
                    models.CharField(choices=[("Business", "Business"), ("Permission", "Permission")], max_length=15),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="files/docs",
                        validators=[django.core.validators.FileExtensionValidator(["pdf", "doc"])],
                    ),
                ),
                (
                    "attachment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_docs",
                        to="users.bankattachment",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
