# Generated by Django 4.2.7 on 2024-03-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_product_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
