# Generated by Django 4.2.7 on 2024-03-15 02:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_profile_phone"),
        ("shop", "0004_cart"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("profile", "product")},
        ),
    ]
