# Generated by Django 4.2.7 on 2024-03-15 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("shop", "0005_alter_cart_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="cart",
            unique_together={("user", "product")},
        ),
        migrations.RemoveField(
            model_name="cart",
            name="profile",
        ),
    ]
