# Generated by Django 4.2.7 on 2024-03-16 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_rename_price_order_total_amount_order_shipping_fee"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="total_amount",
            new_name="amount",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_fee",
        ),
        migrations.AlterField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="order.coupon",
            ),
        ),
    ]
